name: Audit

on:
  push:
    branches:
      - main
    paths:
      - "**.lock"
  pull_request:
    paths:
      - "**.lock"
  schedule:
    - cron: 0 9 * * 1 # Every Monday at 9:00 AM

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16

      - name: Cache Nix Derivations
        uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9
        with:
          use-flakehub: false

      - name: Check Flake
        uses: DeterminateSystems/flake-checker-action@078f5f7f47ee188aa6cb472527ca5984e195222d # v9
        with:
          send-statistics: false

      - name: Run Flake Checks
        run: nix develop --command cargo audit
